<a href="https://colab.research.google.com/github/jcdumlao14/Naive-Bayes-algorithm-/blob/main/MultinominalNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SMS Spam Collection Dataset**

Collection of SMS messages tagged as spam or legitimate

## MultinominalNB

In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/jcdumlao14/Naive-Bayes-algorithm-/main/spam.csv', encoding="ISO-8859-1")
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [2]:
df.info

<bound method DataFrame.info of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN

There are 5,572 observations and 5 columns.

In [3]:
df.groupby('v1').describe()

v2                                                                 \
     count unique                                                top freq   
v1                                                                          
ham   4825   4516                             Sorry, I'll call later   30   
spam   747    653  Please call our customer service representativ...    4   

     Unnamed: 2                                                            \
          count unique                                                top   
v1                                                                          
ham          45     39   bt not his girlfrnd... G o o d n i g h t . . .@"   
spam          5      4                                        PO Box 5249   

          Unnamed: 3                                    Unnamed: 4         \
     freq      count unique                    top freq      count unique   
v1                                                                          
ham     3         10      9                     GE    2          6      5   
spam    2          2      1   MK17 92H. 450Ppw 16"    2          0      0   

                    
          top freq  
v1                  
ham   GNT:-)"    2  
spam      NaN  NaN

In [4]:
df['spam'] =df['v1'].apply(lambda x:1 if x=='spam' else 0)
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  spam  
0        NaN        NaN     0  
1        NaN        NaN     0  
2        NaN        NaN     1  
3        NaN        NaN     0  
4        NaN        NaN     0

In [5]:
df.dropna(axis=1)

v1                                                 v2  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
...    ...                                                ...   ...
5567  spam  This is the 2nd time we have tried 2 contact u...     1
5568   ham              Will Ì_ b going to esplanade fr home?     0
5569   ham  Pity, * was in mood for that. So...any other s...     0
5570   ham  The guy did some bitching but I acted like i'd...     0
5571   ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.v2,df.spam,test_size =0.25)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray() [:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
X_train

2229    haha but no money leh... Later got to go for t...
5108    The sign of maturity is not when we start sayi...
5490                              K. I will sent it again
131               Dear, will call Tmorrow.pls accomodate.
805                                I dled 3d its very imp
                              ...                        
735                         Then why no one talking to me
594     I met you as a stranger and choose you as my f...
5428                     You didnt complete your gist oh.
3610                     No. I.ll meet you in the library
2196           Not much, just some textin'. How bout you?
Name: v2, Length: 4179, dtype: object

In [6]:
!pip install sklearn
import sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=e237dcf753f79ff4c21e93fa83cace0d0f7609368a7c68d62aaee1a6c7eeb95e
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [10]:
import sklearn
print(sklearn.__version__)
print(sklearn.__file__)

1.0.2
/usr/local/lib/python3.7/dist-packages/sklearn/__init__.py


In [11]:
from sklearn.naive_bayes import MultinomialNB 
import numpy as np

model = MultinomialNB()
model.fit(X_train_count, y_train)
print ("Classification rate for NB:")


Classification rate for NB:


In [12]:
emails = ['Go until jurong point, crazy.. Available only ...','Free entry in 2 a wkly comp to win FA Cup fina...']
emails_count = v.transform(emails)
model.predict(emails_count)


array([0, 1])

In [13]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9791816223977028

In [14]:
from sklearn.pipeline import Pipeline
clf =Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [15]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [16]:
clf.score(X_test,y_test)

0.9791816223977028

In [17]:
clf.predict(emails)

array([0, 1])